version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tasks_database
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5432:5432"
